version: "3.7"
x-project-repository-mount:
  &project-repository-mount
  type: bind
  source: $REPOSITORY_PATH
  read_only: true

x-project-base:
  &project-base
  env_file:
    - ../.env
  restart: always
  networks:
    - source-verify
networks:
  source-verify:
volumes:
  db:
  h5ai:
    driver: local

services:
  repository:
    <<: *project-base
    image: ethereum/source-verify:repository-${TAG}
    container_name: repository-${TAG}
    volumes:
      - <<: *project-repository-mount
        target: /data
        read_only: true
    ports:
    - ${REPOSITORY_EXTERNAL_PORT}:${REPOSITORY_PORT}
